// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type Note struct {
	ID    string `json:"id"`
	Title string `json:"title"`
	Text  string `json:"text"`
	Tags  []*Tag `json:"tags"`
}

func (Note) IsNode() {}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type Tag struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

func (Tag) IsNode() {}

type User struct {
	ID              string               `json:"id"`
	Name            string               `json:"name"`
	NotesConnection *UserNotesConnection `json:"notesConnection"`
	TagsConnection  *UserTagsConnection  `json:"tagsConnection"`
}

func (User) IsNode() {}

type UserNoteEdge struct {
	Cursor string `json:"cursor"`
	Node   *Note  `json:"node"`
}

type UserNotesConnection struct {
	Edges      []*UserNoteEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type UserTagEdge struct {
	Cursor string `json:"cursor"`
	Node   *Tag   `json:"node"`
}

type UserTagsConnection struct {
	Edges      []*UserTagEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}
